repos:
-   repo: https://github.com/ambv/black
    rev: 18.9b0
    hooks:
    - id: black
      python_version: python3.6
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-ast
    - id: mixed-line-ending
    - id: debug-statements
-   repo: https://github.com/asottile/pyupgrade
    rev: v1.11.0
    hooks:
    - id: pyupgrade
